package com.cominvi.app.commons.models;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class Accionesmodulos {
	private String descripcion;

	private Date fechahoraalta;

	private long idaccionmodulo;

	private long idempleadoalta;

	private String nombre;


	public Accionesmodulos() {
	}

	public Accionesmodulos(long idaccionmodulo) {
		this.idaccionmodulo = idaccionmodulo;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechahoraalta() {
		return fechahoraalta;
	}

	public void setFechahoraalta(Date fechahoraalta) {
		this.fechahoraalta = fechahoraalta;
	}

	public long getIdaccionmodulo() {
		return idaccionmodulo;
	}

	public void setIdaccionmodulo(long idaccionmodulo) {
		this.idaccionmodulo = idaccionmodulo;
	}

	public long getIdempleadoalta() {
		return idempleadoalta;
	}

	public void setIdempleadoalta(long idempleadoalta) {
		this.idempleadoalta = idempleadoalta;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}