package com.cominvi.app.commons.models;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class AccionesmodulosRoles {
	private Accionesmodulos accionesmodulos;

	private long idaccionesmodulosRoles;

	private Modulos modulos;

	private Roles roles;


	public AccionesmodulosRoles() {
	}

	public AccionesmodulosRoles(long idaccionesmodulosRoles) {
		this.idaccionesmodulosRoles = idaccionesmodulosRoles;
	}

	public Accionesmodulos getAccionesmodulos() {
		return accionesmodulos;
	}

	public void setAccionesmodulos(Accionesmodulos accionesmodulos) {
		this.accionesmodulos = accionesmodulos;
	}

	public long getIdaccionesmodulosRoles() {
		return idaccionesmodulosRoles;
	}

	public void setIdaccionesmodulosRoles(long idaccionesmodulosRoles) {
		this.idaccionesmodulosRoles = idaccionesmodulosRoles;
	}

	public Modulos getModulos() {
		return modulos;
	}

	public void setModulos(Modulos modulos) {
		this.modulos = modulos;
	}

	public Roles getRoles() {
		return roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}
}