package com.cominvi.app.commons.models;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class Dependenciaroles {
	private Date fechahoraalta;

	private long idempleadoalta;

	private long idroldependiente;

	private long idrolmaster;

	private Roles roles;

	private Roles roles2;


	public Dependenciaroles() {
	}

	public Dependenciaroles(long idroldependiente, long idrolmaster) {
		this.idroldependiente = idroldependiente;
		this.idrolmaster = idrolmaster;
	}

	public Date getFechahoraalta() {
		return fechahoraalta;
	}

	public void setFechahoraalta(Date fechahoraalta) {
		this.fechahoraalta = fechahoraalta;
	}

	public long getIdempleadoalta() {
		return idempleadoalta;
	}

	public void setIdempleadoalta(long idempleadoalta) {
		this.idempleadoalta = idempleadoalta;
	}

	public long getIdroldependiente() {
		return idroldependiente;
	}

	public void setIdroldependiente(long idroldependiente) {
		this.idroldependiente = idroldependiente;
	}

	public long getIdrolmaster() {
		return idrolmaster;
	}

	public void setIdrolmaster(long idrolmaster) {
		this.idrolmaster = idrolmaster;
	}

	public Roles getRoles() {
		return roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public Roles getRoles2() {
		return roles2;
	}

	public void setRoles2(Roles roles2) {
		this.roles2 = roles2;
	}
}