package com.cominvi.app.commons.models;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class EmpleadosEmpresas {
	private Empresas empresas;

	private Date fechahoraalta;

	private long idempleado;

	private long idempleadoalta;

	private long idempresa;

	private byte principal;


	public EmpleadosEmpresas() {
	}

	public EmpleadosEmpresas(long idempleado, long idempresa) {
		this.idempleado = idempleado;
		this.idempresa = idempresa;
	}

	public Empresas getEmpresas() {
		return empresas;
	}

	public void setEmpresas(Empresas empresas) {
		this.empresas = empresas;
	}

	public Date getFechahoraalta() {
		return fechahoraalta;
	}

	public void setFechahoraalta(Date fechahoraalta) {
		this.fechahoraalta = fechahoraalta;
	}

	public long getIdempleado() {
		return idempleado;
	}

	public void setIdempleado(long idempleado) {
		this.idempleado = idempleado;
	}

	public long getIdempleadoalta() {
		return idempleadoalta;
	}

	public void setIdempleadoalta(long idempleadoalta) {
		this.idempleadoalta = idempleadoalta;
	}

	public long getIdempresa() {
		return idempresa;
	}

	public void setIdempresa(long idempresa) {
		this.idempresa = idempresa;
	}

	public byte getPrincipal() {
		return principal;
	}

	public void setPrincipal(byte principal) {
		this.principal = principal;
	}
}