package com.cominvi.app.commons.models;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class EmpleadosRoles {
	private Empresas empresas;

	private Date fechahoraalta;

	private long idempleado;

	private long idempleadoalta;

	private long idempleadosRoles;

	private Roles roles;


	public EmpleadosRoles() {
	}

	public EmpleadosRoles(long idempleadosRoles) {
		this.idempleadosRoles = idempleadosRoles;
	}

	public Empresas getEmpresas() {
		return empresas;
	}

	public void setEmpresas(Empresas empresas) {
		this.empresas = empresas;
	}

	public Date getFechahoraalta() {
		return fechahoraalta;
	}

	public void setFechahoraalta(Date fechahoraalta) {
		this.fechahoraalta = fechahoraalta;
	}

	public long getIdempleado() {
		return idempleado;
	}

	public void setIdempleado(long idempleado) {
		this.idempleado = idempleado;
	}

	public long getIdempleadoalta() {
		return idempleadoalta;
	}

	public void setIdempleadoalta(long idempleadoalta) {
		this.idempleadoalta = idempleadoalta;
	}

	public long getIdempleadosRoles() {
		return idempleadosRoles;
	}

	public void setIdempleadosRoles(long idempleadosRoles) {
		this.idempleadosRoles = idempleadosRoles;
	}

	public Roles getRoles() {
		return roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}
}