package com.cominvi.app.commons.models;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class Empleados {
	private String apellidomaterno;

	private String apellidopaterno;

	private int estatus;

	private String fechahoraalta;

	private Date fechahoramod;

	private String fechanacimiento;

	private long idempleado;

	private long idempleadoalta;

	private long idempleadomod;

	private String nombre;

	private int numeronomina;

	private String rfc;


	public Empleados() {
	}

	public Empleados(long idempleado) {
		this.idempleado = idempleado;
	}

	public String getApellidomaterno() {
		return apellidomaterno;
	}

	public void setApellidomaterno(String apellidomaterno) {
		this.apellidomaterno = apellidomaterno;
	}

	public String getApellidopaterno() {
		return apellidopaterno;
	}

	public void setApellidopaterno(String apellidopaterno) {
		this.apellidopaterno = apellidopaterno;
	}

	public int getEstatus() {
		return estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getFechahoraalta() {
		return fechahoraalta;
	}

	public void setFechahoraalta(String fechahoraalta) {
		this.fechahoraalta = fechahoraalta;
	}

	public Date getFechahoramod() {
		return fechahoramod;
	}

	public void setFechahoramod(Date fechahoramod) {
		this.fechahoramod = fechahoramod;
	}

	public String getFechanacimiento() {
		return fechanacimiento;
	}

	public void setFechanacimiento(String fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	public long getIdempleado() {
		return idempleado;
	}

	public void setIdempleado(long idempleado) {
		this.idempleado = idempleado;
	}

	public long getIdempleadoalta() {
		return idempleadoalta;
	}

	public void setIdempleadoalta(long idempleadoalta) {
		this.idempleadoalta = idempleadoalta;
	}

	public long getIdempleadomod() {
		return idempleadomod;
	}

	public void setIdempleadomod(long idempleadomod) {
		this.idempleadomod = idempleadomod;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getNumeronomina() {
		return numeronomina;
	}

	public void setNumeronomina(int numeronomina) {
		this.numeronomina = numeronomina;
	}

	public String getRfc() {
		return rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}
}