package com.cominvi.app.commons.models;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class EmpleadosSistemas {
	private Empresas empresas;

	private Date fechahoraalta;

	private Date fechahoramod;

	private long idempleado;

	private long idempleadoalta;

	private long idempleadomod;

	private long idempleadosSistemas;

	private Sistemas sistemas;


	public EmpleadosSistemas() {
	}

	public EmpleadosSistemas(long idempleadosSistemas) {
		this.idempleadosSistemas = idempleadosSistemas;
	}

	public Empresas getEmpresas() {
		return empresas;
	}

	public void setEmpresas(Empresas empresas) {
		this.empresas = empresas;
	}

	public Date getFechahoraalta() {
		return fechahoraalta;
	}

	public void setFechahoraalta(Date fechahoraalta) {
		this.fechahoraalta = fechahoraalta;
	}

	public Date getFechahoramod() {
		return fechahoramod;
	}

	public void setFechahoramod(Date fechahoramod) {
		this.fechahoramod = fechahoramod;
	}

	public long getIdempleado() {
		return idempleado;
	}

	public void setIdempleado(long idempleado) {
		this.idempleado = idempleado;
	}

	public long getIdempleadoalta() {
		return idempleadoalta;
	}

	public void setIdempleadoalta(long idempleadoalta) {
		this.idempleadoalta = idempleadoalta;
	}

	public long getIdempleadomod() {
		return idempleadomod;
	}

	public void setIdempleadomod(long idempleadomod) {
		this.idempleadomod = idempleadomod;
	}

	public long getIdempleadosSistemas() {
		return idempleadosSistemas;
	}

	public void setIdempleadosSistemas(long idempleadosSistemas) {
		this.idempleadosSistemas = idempleadosSistemas;
	}

	public Sistemas getSistemas() {
		return sistemas;
	}

	public void setSistemas(Sistemas sistemas) {
		this.sistemas = sistemas;
	}
}