package com.cominvi.app.commons.models;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class Empresas {
	private short clase;

	private short comprasregiones;

	private String contpaq;

	private short diasbase;

	private int estatus;

	private Date fechahoraalta;

	private Date fechahoramod;

	private long idempleadoalta;

	private long idempleadomod;

	private long idempresa;

	private byte ieps;

	private String logofull;

	private String logomin;

	private short modificaivaoc;

	private String razonsocial;

	private String rfc;


	public Empresas() {
	}

	public Empresas(long idempresa) {
		this.idempresa = idempresa;
	}

	public short getClase() {
		return clase;
	}

	public void setClase(short clase) {
		this.clase = clase;
	}

	public short getComprasregiones() {
		return comprasregiones;
	}

	public void setComprasregiones(short comprasregiones) {
		this.comprasregiones = comprasregiones;
	}

	public String getContpaq() {
		return contpaq;
	}

	public void setContpaq(String contpaq) {
		this.contpaq = contpaq;
	}

	public short getDiasbase() {
		return diasbase;
	}

	public void setDiasbase(short diasbase) {
		this.diasbase = diasbase;
	}

	public int getEstatus() {
		return estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public Date getFechahoraalta() {
		return fechahoraalta;
	}

	public void setFechahoraalta(Date fechahoraalta) {
		this.fechahoraalta = fechahoraalta;
	}

	public Date getFechahoramod() {
		return fechahoramod;
	}

	public void setFechahoramod(Date fechahoramod) {
		this.fechahoramod = fechahoramod;
	}

	public long getIdempleadoalta() {
		return idempleadoalta;
	}

	public void setIdempleadoalta(long idempleadoalta) {
		this.idempleadoalta = idempleadoalta;
	}

	public long getIdempleadomod() {
		return idempleadomod;
	}

	public void setIdempleadomod(long idempleadomod) {
		this.idempleadomod = idempleadomod;
	}

	public long getIdempresa() {
		return idempresa;
	}

	public void setIdempresa(long idempresa) {
		this.idempresa = idempresa;
	}

	public byte getIeps() {
		return ieps;
	}

	public void setIeps(byte ieps) {
		this.ieps = ieps;
	}

	public String getLogofull() {
		return logofull;
	}

	public void setLogofull(String logofull) {
		this.logofull = logofull;
	}

	public String getLogomin() {
		return logomin;
	}

	public void setLogomin(String logomin) {
		this.logomin = logomin;
	}

	public short getModificaivaoc() {
		return modificaivaoc;
	}

	public void setModificaivaoc(short modificaivaoc) {
		this.modificaivaoc = modificaivaoc;
	}

	public String getRazonsocial() {
		return razonsocial;
	}

	public void setRazonsocial(String razonsocial) {
		this.razonsocial = razonsocial;
	}

	public String getRfc() {
		return rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}
}