package com.cominvi.app.commons.models;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: com.cominvi.app.commons.models.Modulostablas
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class ModulostablasId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("com.cominvi.app.commons.models.Modulostablas"); }
		catch(Exception e) {}
	}

	public long idbasedatos;
	public long idmodulo;
	public long idtabla;

	public ModulostablasId() {
	}

	public ModulostablasId(String str) {
		fromString(str);
	}

	public long getIdbasedatos() {
		return idbasedatos;
	}

	public void setIdbasedatos(long idbasedatos) {
		this.idbasedatos = idbasedatos;
	}

	public long getIdmodulo() {
		return idmodulo;
	}

	public void setIdmodulo(long idmodulo) {
		this.idmodulo = idmodulo;
	}

	public long getIdtabla() {
		return idtabla;
	}

	public void setIdtabla(long idtabla) {
		this.idtabla = idtabla;
	}

	public String toString() {
		return String.valueOf(idbasedatos)
			+ "::" + String.valueOf(idmodulo)
			+ "::" + String.valueOf(idtabla);
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + (int) (idbasedatos ^ (idbasedatos >>> 32));
		rs = rs * 37 + (int) (idmodulo ^ (idmodulo >>> 32));
		rs = rs * 37 + (int) (idtabla ^ (idtabla >>> 32));
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		ModulostablasId other = (ModulostablasId) obj;
		return (idbasedatos == other.idbasedatos)
			&& (idmodulo == other.idmodulo)
			&& (idtabla == other.idtabla);
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		idbasedatos = Long.parseLong(str);
		str = toke.nextToken();
		idmodulo = Long.parseLong(str);
		str = toke.nextToken();
		idtabla = Long.parseLong(str);
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}