package com.cominvi.app.commons.models;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class Roles {
	private String descripcion;

	private byte estatus;

	private Date fechahoraalta;

	private long idempleadoalta;

	private long idrol;

	private String nombre;

	private byte rolmaster;


	public Roles() {
	}

	public Roles(long idrol) {
		this.idrol = idrol;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public byte getEstatus() {
		return estatus;
	}

	public void setEstatus(byte estatus) {
		this.estatus = estatus;
	}

	public Date getFechahoraalta() {
		return fechahoraalta;
	}

	public void setFechahoraalta(Date fechahoraalta) {
		this.fechahoraalta = fechahoraalta;
	}

	public long getIdempleadoalta() {
		return idempleadoalta;
	}

	public void setIdempleadoalta(long idempleadoalta) {
		this.idempleadoalta = idempleadoalta;
	}

	public long getIdrol() {
		return idrol;
	}

	public void setIdrol(long idrol) {
		this.idrol = idrol;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public byte getRolmaster() {
		return rolmaster;
	}

	public void setRolmaster(byte rolmaster) {
		this.rolmaster = rolmaster;
	}
}