package com.cominvi.app.commons.models;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class Sistemas {
	private String descripcion;

	private byte estatus;

	private Date fechahoraalta;

	private Date fechahoramod;

	private long idempleadoalta;

	private long idempleadomod;

	private long idsistema;

	private String logo;

	private String nombre;

	private String version;


	public Sistemas() {
	}

	public Sistemas(long idsistema) {
		this.idsistema = idsistema;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public byte getEstatus() {
		return estatus;
	}

	public void setEstatus(byte estatus) {
		this.estatus = estatus;
	}

	public Date getFechahoraalta() {
		return fechahoraalta;
	}

	public void setFechahoraalta(Date fechahoraalta) {
		this.fechahoraalta = fechahoraalta;
	}

	public Date getFechahoramod() {
		return fechahoramod;
	}

	public void setFechahoramod(Date fechahoramod) {
		this.fechahoramod = fechahoramod;
	}

	public long getIdempleadoalta() {
		return idempleadoalta;
	}

	public void setIdempleadoalta(long idempleadoalta) {
		this.idempleadoalta = idempleadoalta;
	}

	public long getIdempleadomod() {
		return idempleadomod;
	}

	public void setIdempleadomod(long idempleadomod) {
		this.idempleadomod = idempleadomod;
	}

	public long getIdsistema() {
		return idsistema;
	}

	public void setIdsistema(long idsistema) {
		this.idsistema = idsistema;
	}

	public String getLogo() {
		return logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}
}