package com.cominvi.app.commons.models;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class Usuarios {
	private byte bloqueado;

	private byte estatus;

	private Date fechahoraalta;

	private Date fechahoramod;

	private String fechapassword;

	private long idempleado;

	private long idempleadoalta;

	private long idempleadomod;

	private short intentos;

	private String password;


	public Usuarios() {
	}

	public Usuarios(long idempleado) {
		this.idempleado = idempleado;
	}

	public byte getBloqueado() {
		return bloqueado;
	}

	public void setBloqueado(byte bloqueado) {
		this.bloqueado = bloqueado;
	}

	public byte getEstatus() {
		return estatus;
	}

	public void setEstatus(byte estatus) {
		this.estatus = estatus;
	}

	public Date getFechahoraalta() {
		return fechahoraalta;
	}

	public void setFechahoraalta(Date fechahoraalta) {
		this.fechahoraalta = fechahoraalta;
	}

	public Date getFechahoramod() {
		return fechahoramod;
	}

	public void setFechahoramod(Date fechahoramod) {
		this.fechahoramod = fechahoramod;
	}

	public String getFechapassword() {
		return fechapassword;
	}

	public void setFechapassword(String fechapassword) {
		this.fechapassword = fechapassword;
	}

	public long getIdempleado() {
		return idempleado;
	}

	public void setIdempleado(long idempleado) {
		this.idempleado = idempleado;
	}

	public long getIdempleadoalta() {
		return idempleadoalta;
	}

	public void setIdempleadoalta(long idempleadoalta) {
		this.idempleadoalta = idempleadoalta;
	}

	public long getIdempleadomod() {
		return idempleadomod;
	}

	public void setIdempleadomod(long idempleadomod) {
		this.idempleadomod = idempleadomod;
	}

	public short getIntentos() {
		return intentos;
	}

	public void setIntentos(short intentos) {
		this.intentos = intentos;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
}